# Generated by Django 6.0.3 on 2026-03-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('student_image', models.FileField(blank=True, null=True, upload_to='students/')),
                ('father_name', models.CharField(max_length=150)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(blank=True, max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
